### ISSUE TITLE
TODO: meeting 11/10/24

### ISSUE THREAD

**Issue by valeriof7** [tudat-team/tudat-space#152]
1. Documentation Side

- [ ] Lots of new features need documentation
- [ ] Make a list of things that we think are not explained well or not documented at all (on the tudat-space website)
- [ ] Open the issue on tudat-space
- [ ] Documentation of the API Reference Page

2. Tudat-Space Webpage

- [ ] Luigi proposed the following division: Quickstart Guide, Examples, User Guide, Advanced Topics, About
- [ ] In the (near) future, there will be a splitting of the examples: Basic and Advanced.

3. Key API References

- [ ] It is not completely clear how, but the idea is to have very short tables in the Jupyter Notebooks
- [ ] Also, as suggested by Sam and Lars, the API reference should contain links to the relevant examples where the usage of a given class/module is showcased.

4. Common Ground to work on

- [ ] Always base ourselves on DEVELOP branch of tudat and tudatpy
- [ ] run examples: develop, double type
- [ ] new open loop examples: develop, time type
