### ISSUE TITLE
Overview of tudat-space status

### ISSUE THREAD

**Issue by FilippoOggionni** [tudat-team/tudat-space#54]
A (naive?) attempt to keep track of all the issues related to new/existing pages on tudat-space.

**Pages to be written**

- [x] aerodynamic coefficients / aerodynamic guidance (#35)
- [ ] some environment models: Gravity Field Variation, Inertia Tensors, Tabulated atmosphere (#30 and #29)
- [x] spice interface (#51)
- [x] thrust guidance (#32)
- [x] frame transformation (#31)
- [x] plotting utilities (#47)
- [x] troubleshooting (#38)

**Pages to be modified**

- [x] landing page (#21)
- [x] "about" page (#62)
- [x] contribute to tudat-space (#53) 

**Pages to be moved or deleted**

- [x] move content to developer docs (tudat-team/tudat-developer-docs#11)
- [x] other outdated content (#52)

**Comment by DominicDirkx** [comment]
Many thanks for making this overview!

**Comment by FilippoOggionni** [comment]
@DominicDirkx can you please add links of the pages on the old website (tudat.tudelft.nl) which should be migrated to tudat-space?

**Comment by DominicDirkx** [comment]
Pages to consider moving to tudat-space from tudat.tudelft.nl:

- [ ] Discussion of basics of Github http://tudat.tudelft.nl/developerGuide/githubBasics/githubBasics.html. Probably not for tudat-space, but for NA Brightspace page?
- [ ] A list of guides on adding specific features to Tudat http://tudat.tudelft.nl/developerGuide/addingFeatures/index.html This should be transferred, checked, and expanded
- [ ] Basics of using our supported IDE http://tudat.tudelft.nl/developerGuide/qtBasics/qtBasics.html I think this is useful to offer, at least to new students
- [ ] A guide on making a CMakeLists.txt file http://tudat.tudelft.nl/developerGuide/applicationCMakeLists/applicationCMakeLists.html Not so useful, until we make a priority of C++. When we do, a page such as this should be designed from the ground up (?)
- [ ] Guide on writing rst files http://tudat.tudelft.nl/developerGuide/howToWriteTheWiki/howToWriteTheWiki.html Parts of his could be added to the dev docs
